export const dictons: Record<number, Record<number, string>> = {
  1: { // JANVIER
    1: "Jour de l’an beau, mois d’août très chaud.",
    2: "Autant de bonnes journées en janvier, autant de mauvaises en mai.",
    3: "Sainte-Geneviève ne sort point, si Saint-Marcel ne la rejoint.",
    4: "De Sainte-Pharaïlde la chaleur, c’est la colère et notre malheur.",
    5: "À la Saint-Gerlac le temps froid et serein, l’année sera bonne c’est certain.",
    6: "Si le soir du jour des Rois, beaucoup d’étoiles tu vois, auras sécheresse en été, et beaucoup d’oeufs au poulailler.",
    7: "S’il gèle à la Saint-Raymond, l’hiver est encore long.",
    8: "Au jour de Sainte-Gudule, le jour croît, mais le froid ne recule.",
    9: "Pour Saint-Adrien, le froid nous revient.",
    10: "Beau temps à la Saint-Guillaume, donne plus de blé que de chaume.",
    11: "Entre le 10 et le 20 janvier, les plus contents sont les drapiers.",
    12: "Les douze premiers jours de janvier, indiquent le temps qu’il fera les douze mois de l’année.",
    13: "Soleil au jour de Saint-Hilaire, rentre du bois pour ton hiver.",
    14: "Soleil de Ste-Nina, pour un long hiver rentre ton bois.",
    15: "S’il gèle à la Saint-Maur, la moitié de l’hiver est dehors.",
    16: "À la saint Honorat, rarement soleil il y a.",
    17: "À Saint-Antoine grande froidure, à Saint-Laurent grands chauds ne durent.",
    18: "Neige à Ste-Prisca, la belle année que voilà.",
    19: "Janvier de glace fait le point, février, qui passe, le rompt.",
    20: "À la Saint-Sébastien, l’hiver reprend, ou se casse les dents.",
    21: "Jour de Sainte-Agnès, jamais trop de froid ne laisse.",
    22: "À la Saint-Vincent, tout dégèle ou tout fend.",
    23: "Sécheresse de janvier, richesse de fermier.",
    24: "Neige de St-Babylas, bien souvent on s’en lasse.",
    25: "Soleil de St-Priest, abondance de millet.",
    26: "Ste-Paule sec et beau, remplit greniers et tonneaux.",
    27: "Beau temps à la Saint-Julien, promet abondance de biens.",
    28: "À la saint Thomas, le froid n’est jamais loin.",
    29: "S’il gèle à la Saint-Sulpice, le printemps sera propice.",
    30: "Prend garde à la Sainte-Martine, car souvent l’hiver se mutine.",
    31: "À la saint Pierre, l’hiver s’en va ou se resserre."
  },
  2: { // FÉVRIER
    1: "La veille de la chandeleur, l’hiver se passe ou prend vigueur.",
    2: "Rosée à la Chandeleur, hiver à sa dernière heure.",
    3: "S’il ne pleut ou ne neige pour Saint-Blaise, en mars le froid en prendra à son aise.",
    4: "Le lendemain de Saint-Blaise, souvent l’hiver s’apaise, mais si vigueur il reprend, pour longtemps on s’en ressent.",
    5: "Si pour la Sainte-Agathe il pleut, le maïs croit au mieux.",
    6: "À la Sainte-Dorothée, la plus forte neigée.",
    7: "Si février est chaud, croyez bien, sans défaut, que par cette aventure, pâques aura sa froidure.",
    8: "Été de la Saint-Jean, quelques jours cléments.",
    9: "À la Sainte-Apolline, présage certain, l’hiver s’achemine, ou touche à sa fin.",
    10: "Gels matinaux de Saint Arnaud, l’hiver remonte au créneau.",
    11: "Séverin et ses coquins, font tout geler sur leur chemin.",
    12: "Si le soleil luit pour Sainte-Eulalie, pommes et cidre à la folie.",
    13: "De Sainte-Béatrice la nuée Assure six semaines mouillées.",
    14: "À la Saint-Valentin, tous les vents sont marins.",
    15: "À la Saint-Claude, regarde ton seau, tu ne le verras pas plus haut.",
    16: "S’il neige à la Saint-Onésime, la récolte est à l’abîme.",
    17: "Fossés pleins en février, abondance dans les greniers.",
    18: "À la Sainte-Bernadette, souvent le soleil est de la fête.",
    19: "La nouvelle lune de février, sert, pour l’année, de calendrier.",
    20: "Pluie de février, emplit les greniers.",
    21: "À la Saint-Pierre Damien, l’hiver reprend ou s’éteint.",
    22: "Le temps qu’il fait le jour de la Sainte-Isabelle, dure jusqu’aux Rameaux.",
    23: "À la Saint-Florent, l’hiver s’en va ou reprend.",
    24: "En février, si au soleil ton chat tend sa peau, en mars, il l’exposera au fourneau.",
    25: "Vent fort à la saint Nestor, bon vin à la saint Marcellin.",
    26: "Quand il tonne en février, il faut monter les tonneaux au grenier.",
    27: "Gelée du jour Sainte-Honorine, rend toute la vallée chagrine.",
    28: "Beau ciel à la Saint-Romain, il y aura des denrées et du bon vin.",
    29: "L’année bissextile soyez fin, semez du chanvre au lieu du lin."
  },
  3: { // MARS
    1: "Quand il pleut à la Saint-Aubin, l’eau est plus chère que le vin.",
    2: "À la Saint-Joavan dans nos pays, les pies commencent leur nid.",
    3: "A Sainte-Cunégonde le tonnerre, annonce un deuxième hiver.",
    4: "De St-Casimir la douceur, fait peur aux jardiniers et aux laboureurs.",
    5: "À la Saint-Adrien, froidure ne gèle que les nains.",
    6: "Au jour de Sainte-Colette, commence à chanter l’alouette.",
    7: "Le jour de la Sainte-Félicité se voit venir avec gaieté. Car, on l’a toujours remarqué, c’est le plus beau jour de l’année.",
    8: "En mars, les vaches au pré, si ce n’est pour manger, c’est pour s’y gratter.",
    9: "S’il gèle aux 40 Martyrs, il gèlera encore 40 nuits au pire.",
    10: "Pluie de mars grandit l’herbette, et souvent annonce disette.",
    11: "Bon rédeux à Saint-Euloge, voit les jeunes lapins à l’auge.",
    12: "Le jour de Saint-Pol, l’hiver se romp le col.",
    13: "En mars, vent ou pluie, que chacun veille sur lui.",
    14: "Pluie de Sainte-Mahaut, n’est jamais trop.",
    15: "À la mi-mars, le coucou est dans l’épinard.",
    16: "Quand mars se déguise en été, avril prend ses habits fourrés.",
    17: "Quand il fait doux à la Saint-Patrice, de leurs trous sortent les écrevisses.",
    18: "Brouillard en mars, gelée en mai.",
    19: "À la Saint-Joseph beau temps, promesse de bon an.",
    20: "La vigne me dit : En mars me lie, en mars me taille, en mars, il faut qu’on me travaille.",
    21: "Quand, au printemps, la lune est claire, peu de noix espère, si la lune est trouble, la noix redouble.",
    22: "Le mois de mars doit être sec, avril humide et mai frisquet, pour que juin tienne ce qu’il promet.",
    23: "S’il pleut à la Saint-Victorien, on ne ramassera que du foin.",
    24: "S’il gèle au vingt-quatre mars, les poiriers diminuent d’un quart.",
    25: "S’il gèle le 25 mars, pas de grain ni de vin.",
    26: "En mars autant de gelées, En avril autant de poussées.",
    27: "Le soleil de mars donne des rhumes tenaces.",
    28: "À la Saint-Gontran si la température est belle, arrivent les premières hirondelles.",
    29: "Quand mars bien mouillé sera, bien des fruits tu cueilleras.",
    30: "Souvent, la Saint-Amédée, est de mars la plus belle journée.",
    31: "À la Saint-Benjamin, le mauvais temps prend fin."
  },
  4: { // AVRIL
    1: "Pluie de Saint-Hugues à Sainte-Sophie, remplit granges et fournils.",
    2: "Si les quatre premiers jours d’avril sont venteux, il y en aura pour quarante jours.",
    3: "Comme est fait le 3, est fait le mois.",
    4: "À la Saint-Isidore, si le soleil dore, le blé sera haut et chenu, mais le pommier sera nu.",
    5: "Avril entrant comme un agneau, s’en retourne comme un taureau.",
    6: "Au jour de Saint-Prudence, s’il fait du vent, les moutons dansent.",
    7: "En avril, le sureau doit fleurir, sinon, le paysan va souffrir.",
    8: "Mars gris, avril pluvieux, font l’an fertile et plantureux.",
    9: "En avril, ne te découvre pas d’un fil, en mai, fais ce qu’il te plaît.",
    10: "Souvent à Saint-Macaire, reviennent les giboulées d’hiver.",
    11: "S’il gèle à la Saint-Stanislas, on aura deux jours de glace.",
    12: "À la Saint-Jules, mauvais temps, n’est pas installé pour longtemps.",
    13: "Avril frais et mai chaud, remplissent les granges jusqu’en haut.",
    14: "Si Saint-Lambert est pluvieux, suivent neuf jours dangereux.",
    15: "Quand à Saint-Paterne arrive la saison, la chaleur vient pour de bon.",
    16: "Saint-Drogon pluvieux, an fromenteux.",
    17: "Beau temps à la Saint-Anicet, est l’annonce d’un bel été.",
    18: "Avril fait la fleur, mai en a l’honneur.",
    19: "Saint-Ursmar prend, la dernière neige de l’an.",
    20: "À Saint-Théodore, fleurit chaque bouton d’or.",
    21: "Tel temps à la Saint-Anselme, tel temps pendant une semaine.",
    22: "Pluie le jour de Sainte-Opportune, ni cerises, ni prunes.",
    23: "Quand il pleut le jour de Saint-Georges, sur cent cerises, on a quatorze.",
    24: "Entre Georges (23 avril) et Marquet (25 avril), un jour de l’hiver se met.",
    25: "Saint-Marc mouillé au petit jour, c’est de la pluie pour tout le jour.",
    26: "Saint-Clet (ou Anaclet) ferme la porte aux derniers pois.",
    27: "À la Sainte-Zita, le froid ne dure pas.",
    28: "À la Saint-Vital, pluie et gel font tout le mal.",
    29: "Caprices d’avril font tomber les fleurs, et trembler les laboureurs.",
    30: "Saint-Eutrope mouillé, cerises estropiées."
  },
  5: { // MAI
    1: "De la pluie le premier jour de mai, ote aux fourrages de la qualité.",
    2: "Pluie de mai grandit l’herbette, mais c’est signe de disette.",
    3: "Lorsqu’il pleut le 3 mai, point de noix au noyer.",
    4: "Rosée de mai, fait tout beau ou tout laid.",
    5: "Le temps de Sainte-Judith va durer jusqu’au dix.",
    6: "S’il pleut à la petite Saint-Jean, toute l’année s’en ressent, jusqu’à la grande Saint-Jean.",
    7: "Plus mai est chaud, plus l’an vaut.",
    8: "À la Saint-Désiré, tu peux découvrir ton nez.",
    9: "Brouillard de mai et chaleur de juin, amènent la moisson à point.",
    10: "À la Sainte-Solange, on sème les haricots.",
    11: "Les saints de glace. les trois saints au sang de navet, Pancrace, Mamert et Servais, sont bien nommés les saints de glace, Mamert, Servais et Pancrace.",
    12: "Saint-Mamert, Saint-Servais, Saint-Pancrace, de leur passage laissent souvent trace.",
    13: "Avant Saint-Servais, point d’été.",
    14: "Saint-Matthias casse la glace, s’il n’en trouve pas il faut qu’il en fasse.",
    15: "À la Sainte-Denise, le froid n’en fait plus à sa guise.",
    16: "À la Saint-Honoré, s’il fait gelée, le vin diminue de moitié.",
    17: "S’il tonne au jour de Saint-Pascal, sans grêle, ce n’est pas un mal.",
    18: "À Saint-Félix, tous les lilas sont fleuris.",
    19: "À la Saint-Yves, le beau temps arrive.",
    20: "Brouillard de mai, chaleur de juin, amènent la moisson à point.",
    21: "Quand la vigne est en fleur à la Saint-Thiébault, il n’y a ni biens ni maux.",
    22: "À la Sainte-Julie, le soleil ne quitte pas son lit.",
    23: "À la Saint-Didier, soleil orgueilleux, nous annonce un été joyeux.",
    24: "Lorsqu’il pleut à la Saint-Donatien, c’est de la pluie pour le mois qui vient.",
    25: "S’il pleut à la saint Urbain, c’est quarante jours de pluie en chemi.",
    26: "Quand il pleut à la Saint-Philippe, le pauvre n’a pas besoin du riche.",
    27: "À la Saint-Hildevert, est mort tout arbre qui n’est point vert.",
    28: "Soleil de Saint-Germain, nous promet du bon vin.",
    29: "Le jour de Saint-Maximin, s’embaume le jasmin.",
    30: "Celui qui s’allège avant le mois de mai, certainement ne sait pas ce qu’il fait.",
    31: "S’il pleut à la Sainte-Pétronille, pendant quarante jours elle trempe ses guenilles."
  },
  6: { // JUIN
    1: "Pluie de Saint-Révérien, belles avoines, maigre foin.",
    2: "Saint-Marcellin, bon pour l’eau, bon pour le vin.",
    3: "À Sainte-Clotilde, de fleur en buisson, abeille butine à foison.",
    4: "En juin, brume obscure, trois jours seulement dure.",
    5: "Qui en juin se porte bien, au temps chaud ne craindra rien.",
    6: "Les bains que prend Saint-Norbert, inondent toute la terre.",
    7: "Juin froid et pluvieux, tout l’an sera grincheux.",
    8: "S’il pleut à la Saint-Médard, il pleut quarante jours plus tard, à moins que Saint-Barnabé, ne vienne l’arrêter.",
    9: "Juin fait pousser le lin, et juillet le rend fin.",
    10: "À la saint Landry, s’il tonne, restera vide la tonne.",
    11: "À la Saint-Barnabé, fauche ton pré.",
    12: "Pluie de saint Guy, c’est tout l’an qui rit.",
    13: "A la Saint-Antoine de Padoue, toujours de temps doux.",
    14: "À Saint-Rufin, cerises à plein jardin.",
    15: "S’il pleut le quinze juin, il n’y a pas de raisin.",
    16: "Pluie de Saint-Aurélien, bel avoine et mauvais foin.",
    17: "Soleil à la Saint-Hervé, fait présager d’un bel été.",
    18: "Pluie de Saint-Léonce, pour trente jours s’annonce.",
    19: "Saint-Gervais, quand il est beau, tire Médard et Barnabé de l’eau.",
    20: "Pluie d’orage à la Saint-Sylvère, c’est beaucoup de vin dans le verre.",
    21: "Été bien doux, hiver en courroux.",
    22: "À la Saint-Alban, on peut poser ses vêtements.",
    23: "Le sage dit qu’à la Sainte-Audrey, mieux vaut suer que grelotter.",
    24: "Eau de Saint-Jean, peu de vin et pas de froment.",
    25: "Le jour de la Saint-Prosper, n’oublie pas de fumer la terre.",
    26: "En juin trop de pluie, le jardinier s’ennuie.",
    27: "Temps de la Saint-Fernand, chaleur et soleil riant.",
    28: "Le jour de la Saint-Irénée, c’est l’un des plus beaux de l’année.",
    29: "Saint-Pierre et Paul pluvieux, est pour trente jours dangereux.",
    30: "Quand Saint-Pierre laisse de la pluie à Saint-Martial, Saint-Martial donne des essaims autant qu’il en faut."
  },
  7: { // JUILLET
    1: "S’il pleut à la saint Calais, il pleut quarante jours après.",
    2: "La pluie de la Visitation tombe six semaines sur la maison.",
    3: "À Saint-Anatole, confitures dans la casserole.",
    4: "Pour la Sainte-Berthe, se cueille l’amande verte.",
    5: "Si le début de juillet est pluvieux, le restant du mois sera douteux.",
    6: "Jamais, en juillet, sécheresse n’a causé la moindre détresse.",
    7: "Quand à Saint-Raoul le soleil brille, c’est le moissonneur qui grille.",
    8: "À la Saint-Edgar, on entend du coucou le dernier chant.",
    9: "Avec Sainte-Procule, arrive la canicule.",
    10: "Pluie du dix juillet, mouille sept fois, du moissonneur le bonnet.",
    11: "Rosée du jour de Saint-Savin, est, dit-on, rosée de vin.",
    12: "Juillet, orage de nuit, peu de mal, mais que de bruit.",
    13: "À Saint-Henri, suée, mauvaise moissonnée.",
    14: "Pluie du matin, en juillet est bonne au vin.",
    15: "Juillet sans orage, famine au village.",
    16: "Qui veut bon navet, le sème en juillet.",
    17: "À Saint-Alexis, foin occis.",
    18: "À la Saint-Frédéric, tout est vert, tout est nids, plantes, bêtes et gens, tous sourient.",
    19: "À la Saint-Arsène, met au sec tes graines.",
    20: "À la Sainte-Marguerite, forte pluie est maudite.",
    21: "Quand il pleut à la Saint-Victor, la récolte n’est pas d’or.",
    22: "Sainte-Madeleine pluie amène. Si elle ne dure pas longtemps, elle remplit le grenier de froment.",
    23: "Nuages de la Sainte-Brigitte, par le soleil sont chassés vite.",
    24: "À la Sainte-Christine, les blés perdent leurs racines.",
    25: "Si Saint-Jacques est serein, l’hiver sera dur et chagrin.",
    26: "Pour la sainte Anne, s’il pleut, trente jours seront pluvieux.",
    27: "Les Sept Dormants redressent le temps.",
    28: "Si le jour de Saint-Samson, le pinson est au buisson, tu peux, bon vigneron, défoncer ton poinçon.",
    29: "Mauvais temps le jour de Sainte-Marthe, n’est rien, car il faut qu’il parte.",
    30: "À la Sainte-Juliette, l’été est en fête.",
    31: "Au jour de Saint-Ignace, moissonne quelque temps qu’il fasse."
  },
  8: { // AOUT
    1: "S’il pleut au premier août, pas de regain du tout.",
    2: "À la Saint-Eusèbe, au plus tard, fais battre la gerbe.",
    3: "Il faut cueillir les choux, l’un des trois premiers jours d’août.",
    4: "Quand août est bon, abondance à la maison.",
    5: "À Saint-Abel, faites vos confitures de mirabelles.",
    6: "Si le vent souffle le 6 août, le blé sera cher toute l’année. S’il ne souffle pas, il sera bon marché.",
    7: "En août, de l’aube au soir, on n’a qu’une heure pour s’asseoir.",
    8: "À la Saint-Dominique, te plains pas si le soleil pique.",
    9: "Ce qu’août ne mûrit pas, ce n’est pas septembre qui le fera.",
    10: "Froidure à la Saint-Laurent, froidure à la Saint-Vincent.",
    11: "Si, le jour de Sainte-Claire, la journée est chaude et claire, comptez sur les fruits à couteau, à coup sûr ils seront beaux.",
    12: "S’il pleut à la sainte Clarisse, c’est souvent comme vache qui pisse.",
    13: "S’il pleut le jour de Sainte-Radegonde, la misère s’abat sur le monde.",
    14: "Temps trop beau en août, annonce hiver en courroux.",
    15: "Au 15 août, gros nuages en l’air, c’est la neige pour l’hiver.",
    16: "À la Saint-Roch, grande chaleur prépare vin de couleur.",
    17: "À la Saint-Hyacinthe, on peut semer sans crainte.",
    18: "À la Sainte-Hélène, la noix est pleine et le cerneau se met dans l’eau.",
    19: "Quand août est pluvieux, septembre est radieux.",
    20: "Temps de la Saint-Bernard, chaleur et soleil riant.",
    21: "Je suis le mois où nul loisir on ne peut prendre ou séjourner, mais faucher, faner par plaisir, mettre en grange, battre et vanner.",
    22: "Belettes blanches de la St-Symphorien, annoncent que l’hiver est en chemin.",
    23: "À la Sainte-Rose, pour le travailleur, pas de pause.",
    24: "À la Saint-Barthélémy, la grenouille sort de son nid.",
    25: "Beau temps pour la Saint-Louis, plusieurs jours sans pluie.",
    26: "Soleil rouge en août, c’est de la pluie partout.",
    27: "À la Saint-Césaire, la dernière forte chaleur en l’air.",
    28: "C’est comme s’il pleuvait du vin, fine pluie à Saint-Augustin.",
    29: "Pluie à la Sainte-Sabine, est une grâce divine.",
    30: "À la Saint-Fiacre, soleil ardent, pour huit jours encore, du beau temps.",
    31: "En août et en vendanges, il n’y a ni fêtes, ni dimanches."
  },
  9: { // SEPTEMBRE
    1: "S’il fait beau à la Saint-Gilles, cela durera jusqu’à la Saint-Michel.",
    2: "Septembre se nomme, le mai de l’automne.",
    3: "Pluie de Saint-Grégoire, autant de vin en plus à boire.",
    4: "Septembre nous produit, le plus délectable des fruits.",
    5: "Septembre humide, pas de tonneau vide.",
    6: "À la Saint-Onésiphore, la sève s’endort.",
    7: "À la Sainte-Reine, sème tes graines.",
    8: "À la bonne Dame de septembre, tout fruit est bon à prendre.",
    9: "Septembre emporte les ponts, ou tarit les fontaines.",
    10: "À la Sainte-Inès, travaille sans cesse.",
    11: "En septembre si trois jours il tonne, c’est un nouveau bail pour l’automne.",
    12: "En septembre, si tu es prudent, achète grains et vêtements.",
    13: "Le coq, en septembre, chantant la matinée, annonce une abondante rosée.",
    14: "À la Sainte-Croix, cueille tes pommes et gaule tes noix.",
    15: "L’hirondelle en septembre abandonne le ciel refroidi de l’automne.",
    16: "Bel automne vient plus souvent que beau printemps.",
    17: "S’il pleut à la Saint Renaud : l’automne s’annonce penaud.",
    18: "Froid à la Saint-Joseph, annonce pour bientôt la neige.",
    19: "Qui sème à la Saint-Janvier, de l’an récolte le premier.",
    20: "Gelée blanche de Saint-Eustache, grossit le raisin qui tache.",
    21: "Quand il pleut à la Saint-Matthieu, fais coucher tes vaches et tes boeufs.",
    22: "Semis de Saint-Maurice, récolte à ton caprice.",
    23: "Orages de septembre, neiges de décembre.",
    24: "En septembre, la bruine, est toujours bonne à la vigne.",
    25: "Brouillards d’automne, beau temps nous donnent.",
    26: "À la Saint-Côme et Saint-Damien, on trouve des noix plein les chemins.",
    27: "Pluie de septembre travaille, à la vigne et à la semaille.",
    28: "Septembre en sa tournure, de mars fait la figure.",
    29: "Quand les hirondelles voient la Saint-Michel, l’hiver ne vient qu’à Noël.",
    30: "À la Saint-Jérôme, hoche tes pommes."
  },
  10: { // OCTOBRE
    1: "Octobre en bruine, hiver en ruine.",
    2: "Si les feuilles tombent à la Saint-Léger, suivra une bonne année.",
    3: "Octobre en gelées, chenilles trépassées.",
    4: "À la Saint-François, vient le premier froid.",
    5: "À la Saint-Placide, la gelée est la première de l’année.",
    6: "Quand on sème à la Saint-Bruno, la rouille s’y mettra bientôt.",
    7: "À Saint-Serge, achetez vos habits de serge.",
    8: "Gelée d’octobre, rend le vigneron sobre.",
    9: "S’il pleut à la Saint-Denis, la rivière sort neuf fois de son lit.",
    10: "Temps sec à la Saint-Ghislain, annonce un hiver d’eau plein.",
    11: "À la Saint-Firmin, l’hiver est en chemin.",
    12: "Saint-Wilfrid ensoleillé, deux jours plus tard emmitouflé.",
    13: "Brouillards d’octobre et pluvieux novembre, font bon décembre.",
    14: "Beaucoup de pluie en octobre, beaucoup de vent en décembre.",
    15: "Quand octobre prend sa fin, dans la cuve est le raisin.",
    16: "Pour la Saint-Gall, le raisin fait du mauvais vin.",
    17: "Si octobre est chaud, février sera froid.",
    18: "À la Saint-Luc, la pluie du vallon, fait de la neige sur le mont.",
    19: "À la Saint-René, couvre ton nez.",
    20: "Octobre glacé, fait vermine trépasser.",
    21: "À la Sainte-Ursule, le froid recule.",
    22: "À la Saint-Vallier, faut qu’il y ait du bois au bûcher.",
    23: "À la Saint-Jean d’automne, repiquez avant soleil levé.",
    24: "Souvent à la Saint-Florentin, l’hiver laisse son chemin.",
    25: "À la Saint-Crépin, les mouches voient leur fin.",
    26: "À la Saint-Amand, sont mûrs les glands.",
    27: "À la Sainte-Antoinette, la neige s’apprête.",
    28: "Quand Simon et Jude n’apportent pas la pluie, elle n’arrive qu’à la Sainte-Cécile.",
    29: "Neige le jour de Saint-Narcisse, pour le blé est un bénéfice.",
    30: "Tonnerre en octobre, vendanges peu sobres.",
    31: "À la Saint-Quentin, la chaleur a sa fin."
  },
  11: { // NOVEMBRE
    1: "Vent de Toussaint, terreur de marin.",
    2: "Novembre,Toussaint le commande, Saint-André le voit descendre.",
    3: "À la Saint-Hubert, les oies sauvages fuient l’hiver.",
    4: "À Saint-Charles, la gelée parle.",
    5: "Le cinq tu sauras, quel mois tu auras.",
    6: "Quand en novembre il a tonné, l’hiver est avorté.",
    7: "À la Saint-Ernest, abats les pommes qui te restent.",
    8: "Grand soleil, petit vent, petit soleil, grand vent.",
    9: "La Saint-Mathurin, des fruits rouges c’est la fin.",
    10: "Soleil rouge le matin, fait trembler le marin.",
    11: "À la Saint-Martin, l’hiver est en chemin, manchons aux bras et gants aux mains.",
    12: "Temps sanguin, annonce pluie du lendemain.",
    13: "À la Saint-Brice, le temps, sera celui du jour de l’An.",
    14: "Si novembre tonne, l’année suivante sera bonne.",
    15: "À la Saint-Léopold, couvre tes épaules.",
    16: "Brouillard en novembre, l’hiver sera tendre.",
    17: "À Sainte-Élizabeth, tout ce qui porte fourrure n’est point bête.",
    18: "Gelée de novembre, adieu l’herbe tendre.",
    19: "A la Saint-Tanguy, le temps est toujours gris.",
    20: "Entre la Toussaint et l’Avent, attends-toi à pluie et vent.",
    21: "Quelque temps qu’il fasse en novembre, commence le feu dans la chambre.",
    22: "À la Sainte-Cécile, si on plante des pois, ils viennent comme des mâts.",
    23: "Quand l’hiver vient doucement, il est là à la Saint-Clément.",
    24: "À Sainte-Flora, plus rien ne fleurira.",
    25: "À la Sainte-Catherine, tout bois prend racine.",
    26: "À Sainte-Delphine, mets ton manteau à pèlerine.",
    27: "À Saint-Séverin, chauffe tes reins.",
    28: "À Saint-Sosthène, il y a des chrysanthèmes.",
    29: "Quand en novembre la pluie noie la terre, ce sera du bien pour tout l’hiver.",
    30: "Neige de Saint-André, peut cent jours durer."
  },
  12: { // DÉCEMBRE
    1: "Si à la Saint-Éloi tu brûles ton bois, tu auras froid pendant trois mois.",
    2: "Temps clair à la Sainte-Viviane, temps clair pendant quarante jours et une semaine.",
    3: "Décembre prend, il ne rend.",
    4: "À la Sainte-Barbe, soleil peu arde.",
    5: "À la saint Gérald, neige de décembre, c’est pour le jardin cendres.",
    6: "Neige à la Saint-Nicolas donne froid pour trois mois.",
    7: "Quand Saint-Ambroise voit neiger, de dix-huit jours de froid sommes en danger.",
    8: "Jour de l’Immaculée, ne passe jamais sans gelée.",
    9: "De Sainte-Léocadie à Sainte-Nicaise, les gelées naissent.",
    10: "À Sainte-Julie, le soleil ne quitte pas son lit.",
    11: "Tel temps à la Saint-Daniel, même temps à Noël.",
    12: "À la Saint-Corentin, le plein hiver glace le chemin.",
    13: "À la Sainte-Luce, le jour croît d’un saut de puce.",
    14: "Quand en hiver est été, mais en été l’hivernée, cette contrariété, ne fit jamais bonne année.",
    15: "Froid et neige en décembre, du blé à revendre.",
    16: "Le mois de l’Avent est de pluie et de vent, tire ton bonnet jusqu’aux dents.",
    17: "Quand secs sont les Avents, abondant sera l’an.",
    18: "À la Saint-Gatien, le temps ne vaut rien.",
    19: "S’il pleut à la Saint-Urbain, c’est quarante jours de pluie en chemin.",
    20: "Au vingt de Noël, les jours rallongent d’un pas d’hirondelle.",
    21: "Neige de décembre est engrais pour la terre.",
    22: "Décembre trop beau, été dans l’eau.",
    23: "À Saint-Évariste, jour de pluie, jour triste.",
    24: "Beau temps à Sainte-Adèle est un cadeau du ciel.",
    25: "Noël au balcon, Pâques au tison.",
    26: "S’il pleut le jour de saint Étiole, il n’est pas de badioles.",
    27: "Les jours entre Noël et les Rois, indiquent le temps des douze mois.",
    28: "S’il neige à la Sainte-Eléonore, les récoltes seront d’or.",
    29: "S’il gèle à la saint Thomas, il gèlera encore trois mois.",
    30: "Quand il tonne hors saison, pluie et neige sans raison.",
    31: "À la sainte Mélanie, de la pluie n’en veut mie."
  }
};

export function getDicton(date: Date): string {
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const monthDictons = dictons[month];
  if (monthDictons && monthDictons[day]) {
    return monthDictons[day];
  }
  return "";
}
